/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_optimización;

import java.awt.List;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Jucaso
 */
public class solver extends javax.swing.JFrame {

    /**
     * Creates new form solver
     */
    public solver() {
        super("Proyecto optimización");
        initComponents();     
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.jTextArea2.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Input:");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel2.setText("Código de MiniZinc:");

        jButton1.setText("Resolver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Copiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 197, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String codigoMiniZinc = "var int: x_1;"
                                + "\nvar int: x_2;\n";
        String input = jTextArea1.getText() + '\n';           
        StringBuilder sb = new StringBuilder();
        
        int n = 0, nroCiudades = 0;            
        int linea = 0;
        int aux = 0, auxC = 0, x = 0, y = 0;
        ArrayList coordenadasX = new ArrayList();
        ArrayList coordenadasY = new ArrayList();
        
        for (int i = 0; i < input.length(); i++) {           
            if (input.charAt(i) != '\n'){
                //System.out.println("charAt(i): " + input.charAt(i));
                //System.out.println("sb: " + sb.toString());
                if (linea < 2){
                    sb.append(input.charAt(i));  
                }
                else{
                    if (auxC == 1 && input.charAt(i) != ' '){
                           sb.append(input.charAt(i));
                       }
                    if (auxC == 2){
                           sb.append(input.charAt(i));
                       }
                    if (input.charAt(i) == ' '){                        
                        if (auxC == 1){
                            x = Integer.parseInt(sb.toString());
                            //aux = 0;
                            sb.delete(0, sb.length());
                        }
                        auxC++;                      
                    }
                }                           
            }
            else{
                aux = 1;
                auxC = 0;
                y = Integer.parseInt(sb.toString());
            }
            
            if(linea == 0 && aux == 1){
                n = Integer.parseInt(sb.toString());
                linea++;
                aux = 0;
                sb.delete(0, sb.length());
            }
            else if(linea == 1 && aux == 1){
                nroCiudades = Integer.parseInt(sb.toString());
                linea++;
                aux = 0;
                sb.delete(0, sb.length());
            } 
            else if (aux == 1){
                coordenadasX.add(x);
                coordenadasY.add(y);
                aux = 0;
                sb.delete(0, sb.length());
                
            }
        }
        
        System.out.println("n: " + n);
        System.out.println("nroCiudades: " + nroCiudades);
        System.out.println("coordenadasX: " + coordenadasX);
        System.out.println("coordenadasY: " + coordenadasY);
        
        // Creación de restricciones
        
        // Restricciones de que la academia no debe quedar en una ciudad       
        for (int i = 0; i < nroCiudades; i++) {
            codigoMiniZinc = codigoMiniZinc + "constraint abs(x_1 - " + coordenadasX.get(i) + ") + abs(x_2 - " + coordenadasY.get(i) + ") > 0;\n";
        }
        
        // Restricciones triviales
        codigoMiniZinc = codigoMiniZinc + "constraint x_1 >= 0;\n"
                                        + "constraint x_2 >= 0;\n"
                                        + "constraint x_1 <= "+ n +";\n"
                                        + "constraint x_2 <= "+ n +";\n";
        
        // Función a minimizar
        codigoMiniZinc = codigoMiniZinc + "solve minimize ";
        for (int i = 0; i < nroCiudades; i++) {
            if (i < nroCiudades - 1){
                codigoMiniZinc = codigoMiniZinc + "(abs(x_1 - " + coordenadasX.get(i) + ") + abs(x_2 - " + coordenadasY.get(i) + ")) + ";
            }
            else{
                codigoMiniZinc = codigoMiniZinc + "(abs(x_1 - " + coordenadasX.get(i) + ") + abs(x_2 - " + coordenadasY.get(i) + "));\n";
            }
        }       
        // Output    
        codigoMiniZinc = codigoMiniZinc + "output[\"x: \", show(x_1), \" y: \", show(x_2)];";
        //System.out.println(codigoMiniZinc);
        jTextArea2.setText(codigoMiniZinc);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        jTextArea2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String str = jTextArea2.getText();
        Clipboard cb = Toolkit.getDefaultToolkit().getSystemClipboard();
        StringSelection strSel = new StringSelection(str);

        cb.setContents(strSel, null);
        
        JOptionPane.showMessageDialog(this, "Código copiado al portapapeles");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new solver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
